### ISSUE TITLE
Documentation doesn't specify all the requirements

### ISSUE THREAD

**Issue by steven-ellis** [pcuzner/fioloadgen#16]
Python dependency cherrypy
```
./fioservice.py start
Traceback (most recent call last):
  File "./fioservice.py", line 11, in <module>
    from fiotools.server import FIOWebService
  File "/root/fioloadgen/fiotools/server/__init__.py", line 1, in <module>
    from .web import FIOWebService  # NOQA:F401
  File "/root/fioloadgen/fiotools/server/web.py", line 3, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
```

and requests
```
./fiocli.py profile --ls
Traceback (most recent call last):
  File "./fiocli.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
Also need an fio project
```
Error from server (NotFound): namespaces "fio" not found
```

**Comment by steven-ellis** [comment]
It isn't available as an RPM on RHEL8

pip3 install cherrypy

**Comment by steven-ellis** [comment]
yum install python3-requests.noarch

**Comment by pcuzner** [comment]
cherrypy is available for rhel8 - it's in the ceph or ocs repos.

**Comment by pcuzner** [comment]
Will update the docs within the WIP branch
